version: '3'
services:
  rest:
    build: RestServer/.
    links:
    - database
    depends_on: 
    - database
    environment:
    - MONGO_URL=mongodb://database_1:27017/
    ports:
    - "3000:3000"
  application:
    build: ApplicationServer/.
    links:
    - rest
    environment:
    - REST_URL=http://localhost:3000/
    ports:
    - "8080:8080"
  database:
    image: mongo
